# Generated by Django 4.1.2 on 2022-10-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('cree', models.DateTimeField(auto_now_add=True)),
                ('modif', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('estCours', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('priorite', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['priorite'],
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fichier', models.FileField(upload_to='file')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.cours')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Articles.matiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ManyToManyField(to='Articles.classe'),
        ),
    ]
