# Generated by Django 4.1.2 on 2022-10-13 08:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
