# Generated by Django 4.1.2 on 2022-10-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alter_cours_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='desc',
            field=models.CharField(max_length=20),
        ),
    ]
