# Generated by Django 4.1.2 on 2022-10-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_alter_cours_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
