# Generated by Django 4.1.2 on 2022-10-13 13:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_alter_cours_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cours',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
