# Generated by Django 4.1.1 on 2023-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_cours_desc_alter_cours_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
