# Generated by Django 4.1.2 on 2022-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('Photo', models.FileField(upload_to='')),
                ('Role', models.CharField(max_length=50)),
                ('CategorieRole', models.CharField(choices=[('PetitBureau', 'PetitBureau'), ('PoleCordees', 'PoleCordess'), ('PoleCitoyennete', 'PoleCitoyennete'), ('PoleComRE', 'PoleComRE')], max_length=50)),
                ('DefinitionRole', models.CharField(max_length=50)),
                ('FaceBook', models.TextField(null=True)),
                ('Instagram', models.TextField(null=True)),
                ('Linkedin', models.TextField(null=True)),
            ],
        ),
    ]
