# Generated by Django 4.1.2 on 2022-10-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vitrine', '0003_remove_membrebureau_categorierole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrebureau',
            name='CategorieRole',
        ),
        migrations.AddField(
            model_name='membrebureau',
            name='CategorieRole',
            field=models.ManyToManyField(to='Vitrine.polebureau'),
        ),
    ]
