# Generated by Django 4.1.1 on 2023-04-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='matiere',
            field=models.ForeignKey(default='Maths', on_delete=django.db.models.deletion.CASCADE, to='GestionEleves.matiere'),
        ),
    ]
