# Generated by Django 4.1.1 on 2023-04-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEleves', '0002_matiere_eleve_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionEleves.matiere'),
        ),
    ]
